Repository CS2103-AY1819S2-W10-1/main, pull requests merged in 2019-04, with the labels that each got.

#113 [Depends on #111] Delete articles from disk when deleted or archived
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/UnarchiveCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/Entry.java
  src/main/java/seedu/address/storage/ArticleStorage.java
  src/main/java/seedu/address/storage/DataDirectoryArticleStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/util/Network.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/mocks/StorageStub.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/DataDirectoryArticleStorageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEntryTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ContextSwitchSystemTest.java
Labels: priority.Medium, type.Story

#126 Entry Management System: Update find command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/entry/EntryContainsSearchTermsPredicate.java
  src/main/java/seedu/address/model/entry/TitleContainsKeywordsPredicate.java
  src/test/data/JsonSerializableEntryBookTest/typicalEntryEntryBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/EntryBookListParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/entry/EntryContainsSearchTermsPredicateTest.java
  src/test/java/seedu/address/model/entry/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/EntryUtil.java
  src/test/java/seedu/address/testutil/FindEntryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EntryBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, type.Story

#157 Refactor type of urls from String to URL
  src/main/java/seedu/address/commons/util/FeedUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BingWebSearchCommand.java
  src/main/java/seedu/address/logic/commands/FeedCommand.java
  src/main/java/seedu/address/logic/commands/GoogleNewsCommand.java
  src/main/java/seedu/address/logic/parser/BingWebSearchCommandParser.java
  src/main/java/seedu/address/logic/parser/FeedCommandParser.java
  src/main/java/seedu/address/logic/parser/GoogleNewsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entry/EntryContainsSearchTermsPredicate.java
  src/main/java/seedu/address/model/entry/Link.java
  src/main/java/seedu/address/model/entry/util/EntryAutofill.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ArticleStorage.java
  src/main/java/seedu/address/storage/DataDirectoryArticleStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EntryCard.java
  src/main/java/seedu/address/util/Network.java
  src/test/java/guitests/guihandles/EntryCardHandle.java
  src/test/java/seedu/address/commons/util/FeedUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FeedCommandTest.java
  src/test/java/seedu/address/logic/parser/FeedCommandParserTest.java
  src/test/java/seedu/address/mocks/StorageStub.java
  src/test/java/seedu/address/model/entry/LinkTest.java
  src/test/java/seedu/address/storage/DataDirectoryArticleStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
  src/test/java/seedu/address/testutil/EntryUtil.java
  src/test/java/seedu/address/testutil/FindEntryDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/EntryListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/address/util/NetworkTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High

#159 Fix bug where Autofill outputs bad data
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/entry/util/EntryAutofill.java
Labels: priority.High

#160 Update UI to be more user-friendly
  build.gradle
  docs/images/Ui.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ArchivesCommand.java
  src/main/java/seedu/address/logic/commands/FeedCommand.java
  src/main/java/seedu/address/logic/commands/FeedsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/GoogleNewsCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/EntryCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NavigationBar.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/Roboto-Light.ttf
  src/main/resources/fonts/Roboto-LightItalic.ttf
  src/main/resources/fonts/Roboto-Regular.ttf
  src/main/resources/fonts/RobotoSlab-Regular.ttf
  src/main/resources/images/ic_launcher.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NavigationBar.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/ui/EntryCardTest.java
  src/test/java/seedu/address/ui/EntryListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.Enhancement
