Repository CS2103-AY1819S2-W10-1/main, pull requests merged in 2019-03, with the labels that each got.

#31 Set CommandResult, Exception & save EntryBook independently of Command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ManualSetCommandResultExceptionSystemTest.java
Labels: type.Task

#53 Update issue templates
  .github/ISSUE_TEMPLATE/user-story-issue-template.md
Labels: priority.Medium, type.Task

#49 Readme: Remove irrelevant links, add links to additional libraries used
  README.adoc
Labels: priority.High, type.Task

#60 Update Asciidoc settings
  build.gradle
Labels: type.Task

#50 Testing: Consolidate test entries
  src/test/java/seedu/address/network/NetworkTest.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/resources/NetworkTest/default.html
Labels: type.Task

#59 Add thomastanck's Project Portfolio Page
  docs/AboutUs.adoc
  docs/team/thomastanck.adoc
Labels: type.Task
